# Generated by Django 4.1.2 on 2022-11-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total sum'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='with_delivery',
            field=models.BooleanField(verbose_name='With delivery'),
        ),
    ]
