# Generated by Django 4.1.2 on 2022-11-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_orders_end_date_alter_orders_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='with_delivery',
            field=models.BooleanField(default=False, verbose_name='With delivery'),
        ),
    ]
